---
version: 2
updates:
  - package-ecosystem: "gomod"
    # ODF only: disable PR creation, synced from upstream
    open-pull-requests-limit: 0
    directory: "/"
    schedule:
      interval: "monthly"
    rebase-strategy: "disabled"
    labels:
      - "no-API"
    commit-message:
      prefix: "go-ceph"
    groups:
      aws-sdk:
        patterns:
          - "github.com/aws/aws-sdk-*"
  - package-ecosystem: "gomod"
    # ODF only: disable PR creation, synced from upstream
    open-pull-requests-limit: 0
    directory: "/contrib/implements"
    schedule:
      interval: "monthly"
    rebase-strategy: "disabled"
    labels:
      - "no-API"
    commit-message:
      prefix: "contrib"
  - package-ecosystem: "github-actions"
    # ODF only: disable PR creation, synced from upstream
    open-pull-requests-limit: 0
    directory: "/"
    schedule:
      interval: "monthly"
    rebase-strategy: disabled
    labels:
      - "no-API"
    commit-message:
      prefix: "go-ceph"
